### ISSUE TITLE
cannot build environment due to requirements conflict

### ISSUE THREAD

**Issue by palmercd** [lcdb/lcdb-wf#134]
Trying to build top-level conda environment as usual (create -n whatever --file requirements.txt) i now get

Fetching package metadata ...........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - deeptools >=3.0.1
  - numpy >1.15
  - python >=3.6

removing the numpy restriction circumvents it, but i don't know why it was pinned to begin with, so it's probably not actually a solution.

**Comment by daler** [comment]
What are the contents of your `.condarc`?

**Comment by daler** [comment]
sorry, `~/.condarc`

**Comment by palmercd** [comment]
channels:
  - bioconda
  - conda-forge
  - defaults
  - lcdb
default_channels:
  - https://repo.continuum.io/pkgs/free

**Comment by daler** [comment]
try adding `https://repo.continuum.io/pkgs/main` to `defaults:` so it looks like this:

```yaml
channels:
  - bioconda
  - conda-forge
  - defaults
  - lcdb
default_channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/free
```
